[colors.normal]
blue = '#e7c26c'

[colors.selection]
text = '#17130b'
background = '#e7c26c'
 
[colors.cursor]
text = '#eae1d4'
cursor = '#d0c5b4' 
 
[colors.vi_mode_cursor]
text = '#17130b'
cursor = '#e7c26c' 
 
[colors.search.matches]
foreground = '#4d4639' 
background = '#afcfab' 
 
[colors.search.focused_match]
foreground = '#4d4639' 
background = '#e7c26c' 
 
[colors.footer_bar]
foreground = '#4d4639' 
background = '#eae1d4' 
 
[colors.hints.start]
foreground = '#4d4639' 
background = '#d7c5a0' 
 
[colors.hints.end]
foreground = '#4d4639' 
background = '#d7c5a0' 
 
